#----------- Data source
READ_FROM: MQTT
MQTT:
  USERNAME: marcel.walz
  PASSWORD:
  ADDRESS: 192.168.1.80
  PORT: 1883

ZONE_0:
  DEVICE_NAME: Camera_0
  VIDEO_DEVICE: 0
  UUID: fe02d46b-ed11-4304-9241-cb0f7d2dbceb

ZONE_1:
  DEVICE_NAME: Camera_1
  VIDEO_DEVICE: 0
  UUID: 169ef837-ee66-4e1a-8864-1272eba29442


ZONE_2:
  DEVICE_NAME: Camera_2
  VIDEO_DEVICE: 0
  UUID: 4149a70e-e9c3-482b-8e11-3a5c5fe9a32c

ZONE_3:
  DEVICE_NAME: Camera_3
  VIDEO_DEVICE: 0
  UUID: 70d207b2-d813-4a02-8074-6ba4ad77bdfe
