#----------- Data source
READ_FROM: MQTT
MQTT:
  USERNAME: marcel.walz
  PASSWORD:
  ADDRESS: localhost
  PORT: 1883

#---------- Subtopics to publish for each Zone
SUBTOPIC:
  - idle_patientzone
  - data/patient_zone/thermal/event

#---------- Types of data the sensor units send out and their abbreviation
READING:
  THERMAL: TZ_
  TOF: ToFZ_

#----------- Sensor related config
FOV:
  TOF_BIG: 45     # Big 8x8 sensor: 45deg,
  TOF_SMALL: 20   # Small sensor all SPADs: ~20deg
  THERMAL: 40
RESOLUTION:
  # TOF: is dynamic. Either 8,4,3 or 2
  THERMAL: 8  # 8x8


#----------- Visualizer specific config
TEMP:
  MIN: 19 # degrees
  MAX: 26
VIEW_LIMITS:
  - 5 # X meters
  - 5 # Y meters

#----------- Environment specific config
CEILING_HEIGHT: 288  # cm
ZONE_0: # Neue Zone am Fussende schief aufs Bett
  MAC_ADDRESS: EC:8D:88:35:49:F9
  NAME: foot_new
  LOC:
    - 0
    - -1.45
ZONE_1: # Alte Zone am Fussende schief aufs Bett
  MAC_ADDRESS: F8:60:BB:C0:58:A6
  NAME: foot_old
  LOC:
    - 0
    - -1.45
ZONE_2: # Rechte zone - vom Fußende gesehen rechts
  MAC_ADDRESS: F0:4C:E9:43:98:AF
  NAME: ToF_right
  LOC:
    - 1
    - 0
ZONE_3: # Linke zone
  MAC_ADDRESS: CC:F4:CF:F7:44:85
  NAME: ToF_left
  LOC:
    - -1 # von mitte des bettes 1m nach links
    - 0

ZONE_4: # Next Gen Sensor
  MAC_ADDRESS: DA:6D:19:9F:D4:71
  NAME: Next_Gen