#----------- Data source
READ_FROM: RGB
MQTT:
  USERNAME: marcel.walz
  PASSWORD:
  ADDRESS: 192.168.1.80
  ADDRESS-L: localhost
  PORT: 1883

CAMERA:
  DEVICE_NAME: RGB_Test_Camera
  VIDEO_DEVICE: 0
  UUID: fe02d46b-ed11-4304-9241-cb0f7d2dbceb
